server:
  port: 8100

#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/ry-vue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#          username: root
#          password: 123456
#        slave_1:
#          url: jdbc:mysql://localhost:3306/ry-vue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#          username: root
#          password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-vue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379 #端口
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: 60000ms
        max-idle: 20
        min-idle: 1
#mybatis
mybatis-plus:
  typeAliasesPackage: com.pj.mybatisPlus.entity
  mapper-locations: classpath*:mapper/*Dao.xml
  global-config:
    id-type: auto
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.loggong.stdout.StdOutImpl
logging:
  level:
    com: debug
